//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectoESGPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointement
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Diagnosis { get; set; }
        public string Medication { get; set; }
        public string Obs { get; set; }
        public string Doctor { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
