//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectoESGPS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CData
    {
        public int Id { get; set; }
        public string Altura { get; set; }
        public string Peso { get; set; }
        public string Alergias { get; set; }
        public string SPO2 { get; set; }
        public string HR { get; set; }
        public string PS { get; set; }
        public string Temp { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
