//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectoESGPS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelDiagramaBDContainer : DbContext
    {
        public ModelDiagramaBDContainer()
            : base("name=ModelDiagramaBDContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Appointement> AppointementSet { get; set; }
        public virtual DbSet<Patient> PatientSet { get; set; }
        public virtual DbSet<CData> CDataSet { get; set; }
        public virtual DbSet<Files> FilesSet { get; set; }
    }
}
